SELECT TOP 10 *
FROM customer_shopping_behavior

-- Q1.what is the total revenue generated by male vs feamale customers

select gender, sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by gender

-- Q2.which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer_shopping_behavior
where discount_applied = 'yes' and purchase_amount >=( select AVG(purchase_amount) from customer_shopping_behavior)

-- Q3.which are the top 5 products with highest average review rating?

select top 5 item_purchased , round(avg(review_rating),2) as avg_review_rating
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc

-- Q4.compare the average purchase amounts between standard and express shipping
 
 select shipping_type, avg(purchase_amount)
 from customer_shopping_behavior
 where shipping_type in ('standard','express')
 group by shipping_type

 -- Q5.do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
 select subscription_status,count(*) as total_customers, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
 from customer_shopping_behavior
 group by subscription_status
 
 -- Q6.which 5 products have the highest percentage of purchases with discounts applied

 select top 5 item_purchased,
             (100 *  sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*))as discount_rate
			   from customer_shopping_behavior
			   group by item_purchased
			   order by discount_rate desc

-- Q7.segment customers into new , returning, and loyal based on their total number of previous purchases, and show the count of each segment

with customer_segments as
(  
  select
     case
	  when previous_purchases = 1 then 'new'
	  when previous_purchases between 2 and 10 then 'returning'
	  else 'loyal'
     end as customer_segment
   from customer_shopping_behavior
)
select customer_segment, count(*) as customer_segment
from customer_segments
group by customer_segment

-- Q8.what are the top 3 most purchased  products within each category

 with item_counts as (
 select category,
 item_purchased,
 count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customer_shopping_behavior
 group by category, item_purchased
 )

 select item_rank, category, item_purchased,total_orders 
 from item_counts
 where item_rank<=3;

 -- Q9.Are Customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
  
  select subscription_status,
  count(customer_id) as repeat_buyers
  from customer_shopping_behavior
  where previous_purchases > 5
  group by subscription_status

  -- Q10.What is the revenue contribution of each age group?

   select age_group,
   sum(purchase_amount) as total_revenue
   from customer_shopping_behavior
   group by age_group
   order by total_revenue desc